name: bbb

on:
    workflow_dispatch:
    schedule:
        - cron: "20,30 12,19 * * *"
    watch:
        types: [started]

jobs:
    build: 
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【bbb】"
              if: env.BBB_COOKIE
              run: |
                  node Task/BBB.js
              env:
                  BBB_COOKIE: ${{ secrets.BBB_COOKIE }}
