name: ZQKD

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '1,59 6-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【ZQKD】'
        run: |
          node Task/youthshare.js
